FROM verificarlo/fuzzy:v0.5.0-lapack-python3.8.5-numpy-scipy-sklearn AS buider

ENV VFC_BACKENDS "libinterflop_ieee.so"

COPY . /opt/build/pytracer 

RUN cd /opt/build/pytracer && \
    pip3 install . -r requirements-fuzzy.txt

RUN cd /opt/build/ &&\
    git clone -b 0.6 --depth=1 https://github.com/yeatmanlab/pyAFQ.git &&\
    cd /opt/build/pyAFQ &&\
    sed -i 's/numpy==1.18.5/numpy>=1.18.5,<1.20/g' setup.cfg &&\
    sed -i 's/cvxpy==1.1.5/cvxpy>=1.1.10/g' setup.cfg &&\
    pip3 install .

ENV PYTRACER_CONFIG /opt/build/pytracer/pytracer/data/config/config.json

CMD ["pytracer trace --module "]

FROM builder 

RUN cd /opt/build/pytracer && \
    pytest --script-launch-mode=subprocess --nsamples=3 -m "not slow" -v -k "trace_only and ufunc_off"
RUN cd /opt/build/pytracer && \
    pytest --script-launch-mode=subprocess --nsamples=3 -m "not slow" -v -k "trace_only and ufunc_on"
RUN cd /opt/build/pytracer && \
    pytest --script-launch-mode=subprocess --nsamples=3 -m "not slow" -v -k "trace_parse"

ENTRYPOINT [ "/bin/bash" ]