FROM verificarlo/fuzzy:v0.5.0-lapack-python3.8.5-numpy AS builder

COPY . /opt/build/pytracer 

RUN cd /opt/build/pytracer && \
    pip3 install . -r requirements.txt

ENV PYTRACER_CONFIG /opt/build/pytracer/pytracer/data/config/config.json

CMD ["pytracer trace --module "]

# FROM builder 

RUN cd /opt/build/pytracer && \
    pytest --script-launch-mode=subprocess --nsamples=3 -m "not slow" -v -k "trace_only and ufunc_off"
RUN cd /opt/build/pytracer && \
    pytest --script-launch-mode=subprocess --nsamples=3 -m "not slow" -v -k "trace_only and ufunc_on"
RUN cd /opt/build/pytracer && \
    pytest --script-launch-mode=subprocess --nsamples=3 -m "not slow" -v -k "trace_parse"

ENTRYPOINT [ "/bin/bash" ]