FROM yohanchatelain/fuzzy:v0.7.2-lapack-python3.8.5-numpy-scipy-sklearn as builder

ENV VFC_BACKENDS "libinterflop_ieee.so"

COPY . /opt/build/pytracer 

ENV CC=gcc
ENV CXX=g++

RUN git clone https://github.com/verificarlo/significantdigits.git /opt/build/significantdigits && \
    cd /opt/build/significantdigits && \
    python3 -m pip install . -r requirements_docker.txt

RUN cd /opt/build/pytracer && \
    pip3 install . -r requirements-fuzzy.txt

RUN cd /opt/build/ &&\
    git clone -b 0.6 --depth=1 https://github.com/yeatmanlab/pyAFQ.git &&\
    cd /opt/build/pyAFQ &&\
    sed -i 's/numpy==1.18.5/numpy>=1.18.5,<1.20/g' setup.cfg &&\
    sed -i 's/cvxpy==1.1.5/cvxpy>=1.1.10/g' setup.cfg &&\
    pip3 install .

ENV PYTRACER_CONFIG /opt/build/pytracer/pytracer/data/config/config.json

CMD ["pytracer trace --module "]

FROM builder 

RUN cd /opt/build/pytracer && \
    pytest -x --script-launch-mode=subprocess --nsamples=3 -m "not slow" -v -k "trace_only"
RUN cd /opt/build/pytracer && \
    pytest -x --script-launch-mode=subprocess --nsamples=3 -m "not slow" -v -k "trace_parse"

ENTRYPOINT [ "/bin/bash" ]